# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190118_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
