# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-19 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190118_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='password',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
