# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-19 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190119_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='mobile',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='password',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
