# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190123_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_category', to='app.Group', verbose_name='\u7fa4\u7ec4'),
        ),
    ]
